name: cinematica
description: A new Flutter project.preferred for private packages.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Utils
  flutter_localizations:
    sdk: flutter
  google_fonts: ^5.0.0
  dio: ^5.2.0+1
  pretty_dio_logger: ^1.1.1
  flutter_svg: ^2.0.4
  intl: ^0.18.0
  carousel_slider: ^4.2.1
  sliding_up_panel: ^2.0.0+1
  shimmer: ^3.0.0
  flutter_secure_storage: ^8.0.0
  path_provider: ^2.0.15
  shared_preferences: ^2.1.2
  image_picker: ^1.0.0
  path: ^1.8.3
  firebase_storage: ^11.2.4
  firebase_core: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  assets:
    - assets/images/

  generate: true
  uses-material-design: true